complete issue 146
womenhackfornonprofits/whfnp pull request #149
Opened 2016-10-02 13:24 UTC by herecomesjaycee

@womenhackfornonprofits/whfnp

## Linked Jira/Github Issue Ticket
https://github.com/womenhackfornonprofits/whfnp/issues/146
## What are the changes included in this PR?
Edit volunteer.html to include bootstrap grid
## If the changes are visual, provide a screenshot.
Visual screenshots are provided on the issue146 ticket

2016-10-02 17:20 UTC, VAO11 reviewed
Hey Jaycee, Great work. he ony thing I noticed was the spacing of the how it works section. It has changed from the  original view.

![image](https://cloud.githubusercontent.com/assets/20387843/19022276/9818a81e-88cc-11e6-9592-cb530b8de0cd.png)

I think this can resolved by replacing the div class = "col-wrap" (css)  with div class="container" (bootstrap).

2016-10-02 18:11 UTC, VAO11 reviewed
Great! It back to normal now.

2016-10-03 09:11 UTC, lili2311 requested changes

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +    <div class="col-sm-6 col-md-5 col-md-offset-2 col-lg-6 col-lg-offset-0">
Why do we need `col-lg-offset-0`? That does an offset of 0 columns, can it be removed unless it does something special?

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +      <div class="col-md-4 centered-text" align="center">
align="center" what does this do? This is not valid inline css (also please no inline css, all css to be in the css files), please can we the bootsrap centering class.

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +      <div class="col-md-4" align="center">
same here

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +      <div class="col-md-4" align="center">
same here

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
>    <div class="volunteers-wrap">
`volunteer-wrap` doesn't exist in the css, please remove this and the div

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +    <div class="col-sm-6 col-md-5 col-md-offset-2 col-lg-6 col-lg-offset-0">
`col-lg-offset-0` here as well

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +    </div>
Please can the HTML be formatted with correct spacing? usually 4 spaces, this is a good place to use: http://www.cleancss.com/html-beautify/ or in the text editor can use the spacing it provides or a [linter](https://github.com/SublimeLinter/SublimeLinter-html-tidy).

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +    <div class="col-sm-6 col-md-5 col-md-offset-2 col-lg-6 col-lg-offset-0">
`col-lg-offset-0` here

2016-10-03 09:11 UTC, lili2311 commented on src/volunteers.html
> +        <img class="volunteer-picture" src="img/volunteers/Anna_Leach.png" alt="Anna Leach Picture" >
extra space at the end of the html tag, please remove

2016-10-04 09:28 UTC, lili2311 requested changes

2016-10-04 09:28 UTC, lili2311 commented on src/volunteers.html
> +            <h1 class="title-heading title-cta">Volunteers</h1><a class="button" href="volunteer-contact.html">Volunteer with us</a>
`title-cta` is not a class anywhere else and has no entry in the css files, please remove.

2016-10-04 09:32 UTC, lili2311 approved these changes

2016-10-04 09:32 UTC, lili2311 commented
👍 perfect ty! merging

2016-10-06 19:53 UTC, merged