Issue 148
womenhackfornonprofits/whfnp pull request #151
Opened 2016-10-04 23:43 UTC by VAO11

@womenhackfornonprofits/whfnp

## Linked Jira/Github Issue Ticket
Issue #148 
## What are the changes included in this PR?
Replaces the sass with bootstrap.  Removed the redundant content
## If the changes are visual, provide a screenshot.

Completed Desktop View:
![dtp-projects-bs](https://cloud.githubusercontent.com/assets/20387843/19096241/c5391136-8a92-11e6-9aa2-26391be1341e.PNG)

Completed Desktop View:
![dtp-projects-bs2](https://cloud.githubusercontent.com/assets/20387843/19096359/aee804b8-8a93-11e6-8e18-31f9328792bc.PNG)

Mobile View:
![photo339689204415047709](https://cloud.githubusercontent.com/assets/20387843/19096493/b053dad8-8a94-11e6-82d7-8ddcf40d0253.jpg)
![photo339689204415047708](https://cloud.githubusercontent.com/assets/20387843/19096492/b0512f0e-8a94-11e6-9885-2ead119f7b19.jpg)

2016-10-05 15:59 UTC, lili2311 commented
Seems the projects are now not longer left aligned? Can we please add that back?

2016-10-05 16:02 UTC, VAO11 commented
Not sure what you mean? Are you referring to the images or text?

2016-10-05 16:03 UTC, lili2311 commented
The title and button are now centered, on the live site they are left aligned: http://www.womenhackfornonprofits.com/projects.html

2016-10-06 21:14 UTC, lili2311 commented
let me know once you pushed the changes so we can merge and deploy this :)

2016-10-20 21:54 UTC, lili2311 requested changes

2016-10-20 21:54 UTC, lili2311 commented on src/projects.html
> +                <!--img src="" class="" alt="fashrevwall" /-->
please remove commented out code

2016-10-20 21:55 UTC, lili2311 commented on src/projects.html
> +                <!--img src="" class="" alt="fashrevwall" /-->
apart from that 👍  merge away

2016-10-23 17:29 UTC, VAO11 reviewed
Comments removed, Grunt files amended. Can this now be merged into Dev?

2016-10-23 21:24 UTC, merged